# Exercise 2.C Working with multiple DataFrames

In [1]:
import numpy as np
import pandas as pd

## Basic Aggregations

In [3]:
# Creating the dataframe
data = {'Product':    ['A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'],   # 9 items
        'Region':     ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North'],  # 9 items
        'Units_Sold': [10, 15, 20, 5, 10, 15, 10, 5, 15],               # 9 items
        'Price':      [100, 200, 150, 100, 200, 150, 100, 200, 150]}  
df_sales = pd.DataFrame(data)
df_sales

  Product Region  Units_Sold  Price
0       A  North          10    100
1       B  South          15    200
2       C   East          20    150
3       A   West           5    100
4       B  North          10    200
5       C  South          15    150
6       A   East          10    100
7       B   West           5    200
8       C  North          15    150

In [4]:
# Adding a revenue column by multiplying Units_Sold and Price for each row
df_sales['Revenue'] = df_sales['Units_Sold'] * df_sales['Price']
df_sales

  Product Region  Units_Sold  Price  Revenue
0       A  North          10    100     1000
1       B  South          15    200     3000
2       C   East          20    150     3000
3       A   West           5    100      500
4       B  North          10    200     2000
5       C  South          15    150     2250
6       A   East          10    100     1000
7       B   West           5    200     1000
8       C  North          15    150     2250

In [5]:
# Calculate total Units_Sold and total Revenue across all products and regions
df_sales[['Units_Sold', 'Revenue']].sum()

Units_Sold      105
Revenue       16000
dtype: int64

In [6]:
# Caluclate average Units_Sold and average Revenue across all rows
df_sales[['Units_Sold', 'Revenue']].mean()

Units_Sold      11.666667
Revenue       1777.777778
dtype: float64

## Grouping Data

In [7]:
# Group by Product and sum Units_Sold and Revenue for each product
df_sales.groupby('Product')[['Units_Sold', 'Revenue']].sum()

         Units_Sold  Revenue
Product
A                25     2500
B                30     6000
C                50     7500

In [8]:
# Group by Region and caluclate average Units_Sold and Revenue for each region
df_sales.groupby('Region')[['Units_Sold', 'Revenue']].mean()

        Units_Sold  Revenue
Region
East     15.000000   2000.0
North    11.666667   1750.0
South    15.000000   2625.0
West      5.000000    750.0

In [9]:
# Group by both Product and Region, then sum Units_Sold and Revenue for each combination 
df_sales.groupby(['Product', 'Region',])[['Units_Sold', 'Revenue']].sum()

                Units_Sold  Revenue
Product Region
A       East            10     1000
        North           10     1000
        West             5      500
B       North           10     2000
        South           15     3000
        West             5     1000
C       East            20     3000
        North           15     2250
        South           15     2250

## Sorting and Ranking Data

In [10]:
# Sort df_sales by Units_Sold in ascending order
df_sales.sort_values('Units_Sold')

  Product Region  Units_Sold  Price  Revenue
3       A   West           5    100      500
7       B   West           5    200     1000
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
1       B  South          15    200     3000
5       C  South          15    150     2250
8       C  North          15    150     2250
2       C   East          20    150     3000

In [11]:
# Sort df_sales by Revenue in descending order
df_sales.sort_values('Revenue', ascending=False)

  Product Region  Units_Sold  Price  Revenue
1       B  South          15    200     3000
2       C   East          20    150     3000
8       C  North          15    150     2250
5       C  South          15    150     2250
4       B  North          10    200     2000
0       A  North          10    100     1000
6       A   East          10    100     1000
7       B   West           5    200     1000
3       A   West           5    100      500

In [13]:
# Add a Revenue_Rank column with rank 1 being the highest revenue
df_sales['Revenue_Rank'] = df_sales['Revenue'].rank(ascending=False).astype(int)
df_sales # review sales with the new Revenue_Rank column

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank
0       A  North          10    100     1000             7
1       B  South          15    200     3000             1
2       C   East          20    150     3000             1
3       A   West           5    100      500             9
4       B  North          10    200     2000             5
5       C  South          15    150     2250             3
6       A   East          10    100     1000             7
7       B   West           5    200     1000             7
8       C  North          15    150     2250             3

## Merging DataFrames

In [14]:
# Create df_products mapping each Product to its Category
product_data = {'Product': ['A', 'B', 'C'],
                'Category': ['Electronics', 'Furniture', 'Appliances']}
df_products = pd.DataFrame(product_data)
df_products

  Product     Category
0       A  Electronics
1       B    Furniture
2       C   Appliances

In [16]:
# Merge df_sales and df_products on the shared Product column
df_merged = pd.merge(df_sales, df_products, on='Product')
# This is an inner join by default so only the matching products are kept
df_merged

  Product Region  Units_Sold  Price  Revenue  Revenue_Rank     Category
0       A  North          10    100     1000             7  Electronics
1       B  South          15    200     3000             1    Furniture
2       C   East          20    150     3000             1   Appliances
3       A   West           5    100      500             9  Electronics
4       B  North          10    200     2000             5    Furniture
5       C  South          15    150     2250             3   Appliances
6       A   East          10    100     1000             7  Electronics
7       B   West           5    200     1000             7    Furniture
8       C  North          15    150     2250             3   Appliances

In [17]:
# Group df_merged by Category and sum Revenue to see which category earns the most 
df_merged.groupby('Category')['Revenue'].sum()

Category
Appliances     7500
Electronics    2500
Furniture      6000
Name: Revenue, dtype: int64